# This is a basic workflow to help you get started with Actions
name: CI laravel project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: configure PHP 8.0
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring , ctype , fileinfo , PDO , bcmath , json , tokenizser , xml
          

      # Runs a set of commands using the runners shell
      - name: install composer
        run: |
          composer update --no-dev --no-interaction --prefer-dist
          echo install composer done.

      # Runs a set of commands using the runners shell
      - name: Compiled css files
        run: |
          npm install
          npm run build
          echo install npm done.
